apiVersion: apps/v1
kind: Deployment
metadata:
  name: abi-isp-be
  namespace: abi-isp-staging
spec:
  selector:
    matchLabels:
      app: abi-isp-be
  replicas: 1
  template:
    metadata:
      labels:
        app: abi-isp-be
    spec:
      containers:
        - name: abi-isp-be
          image: git.empatnusabangsa.com/empatnusabangsa/abi-isp-be:<VERSION>
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: abi-isp-be-env
      imagePullSecrets:
        - name: regcred

