apiVersion: v1
kind: Service
metadata:
  name: abi-isp-be
  namespace: abi-isp-staging
  labels:
    run: abi-isp-be
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app:  abi-isp-be
